version: "3"
services:

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=dev
      - MYSQL_ROOT_PASSWORD=test
    ports:
      - "3306:3306"

  # backend:
  #   build:
  #     context: ./
  #     dockerfile: Dockerfile
  #   image: fesl-backend:latest
  #   links:
  #     - mysql:mysql
  #   # env_file: dev.env
  #   environment:
  #     - GAMESPY_IP=0.0.0.0
  #     - THEATER_ADDR=127.0.0.1
  #     - TELEMETRY_TOKEN=none
  #     - DATABASE_HOST=mysql
  #     - DATABASE_PORT=3306
  #     - DATABASE_USERNAME=root
  #     - DATABASE_PASSWORD=test
  #     - DATABASE_NAME=dev
  #   ports:
  #     # "FESL_CLIENT_PORT"
  #     - "18270:18270"
  #     # "FESL_SERVER_PORT"
  #     - "18051:18051"
  #     # "THEATER_CLIENT_PORT"
  #     - "18275:18275"
  #     # "THEATER_SERVER_PORT"
  #     - "18056:18056"

  # server:
  #   image: bfh-server:1.42
  #   extra_hosts:
  #     - "somehost:162.242.195.82"


  # mongo:
  #   image: mongo:3-jessie

  # nats:
  #   image: nats:1.0.4-linux
  #   ports:
  #     - "4222:4222" # for clients
  #     - "6222:6222" # a routing port for clustering
  #     - "8222:8222" # an HTTP management port for information reporting
